"""Added Payment Table

Revision ID: 07fc4e25cfc0
Revises: 22b82da2e2f2
Create Date: 2023-07-13 00:45:17.931791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fc4e25cfc0'
down_revision = '22b82da2e2f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('order_id', sa.String(length=30), nullable=True),
    sa.Column('payment_id', sa.String(length=30), nullable=True),
    sa.Column('arn', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('payment_gateway', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['arn'], ['applications.arn'], ),
    sa.PrimaryKeyConstraint('arn'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_details')
    # ### end Alembic commands ###
