"""applications table altered

Revision ID: 2d744dbd9cae
Revises: 7c3926013d64
Create Date: 2023-07-13 20:12:58.899461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d744dbd9cae'
down_revision = '7c3926013d64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
