"""users table altered

Revision ID: 38bb9bec42f8
Revises: 07fc4e25cfc0
Create Date: 2023-07-13 17:21:33.128194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38bb9bec42f8'
down_revision = '07fc4e25cfc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_passport_offices_po_code', table_name='passport_offices')
    op.create_index(op.f('ix_passport_offices_po_code'), 'passport_offices', ['po_code'], unique=False)
    op.create_index(op.f('ix_passport_offices_rpo'), 'passport_offices', ['rpo'], unique=False)
    op.add_column('users', sa.Column('scopes', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'scopes')
    op.drop_index(op.f('ix_passport_offices_rpo'), table_name='passport_offices')
    op.drop_index(op.f('ix_passport_offices_po_code'), table_name='passport_offices')
    op.create_index('ix_passport_offices_po_code', 'passport_offices', ['po_code'], unique=False)
    # ### end Alembic commands ###
