"""appointments schedule table altered

Revision ID: 3ef40017fe53
Revises: 2d744dbd9cae
Create Date: 2023-07-15 21:16:27.956812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef40017fe53'
down_revision = '2d744dbd9cae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_schedules', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_appointment_schedules_date'), 'appointment_schedules', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_schedules_date'), table_name='appointment_schedules')
    op.alter_column('appointment_schedules', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
