"""tables altered

Revision ID: 4877cc7f1eaf
Revises: 68a6db1c3319
Create Date: 2023-07-18 22:12:11.929090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4877cc7f1eaf'
down_revision = '68a6db1c3319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_police_stations_id'), 'police_stations', ['id'], unique=False)
    op.drop_constraint('applicant_addresses_ibfk_1', 'applicant_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'applicant_addresses', 'applications', ['arn'], ['arn'], ondelete='CASCADE')
    op.drop_constraint('applicant_family_ibfk_1', 'applicant_family', type_='foreignkey')
    op.create_foreign_key(None, 'applicant_family', 'applications', ['arn'], ['arn'], ondelete='CASCADE')
    op.drop_constraint('applications_ibfk_1', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('appointment_schedules_ibfk_1', 'appointment_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_schedules', 'passport_offices', ['po_code'], ['po_code'], ondelete='CASCADE')
    op.drop_constraint('appointments_ibfk_1', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_ibfk_2', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'applications', ['arn'], ['arn'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'passport_offices', ['po_code'], ['po_code'], ondelete='CASCADE')
    op.drop_constraint('payment_details_ibfk_1', 'payment_details', type_='foreignkey')
    op.create_foreign_key(None, 'payment_details', 'applications', ['arn'], ['arn'], ondelete='CASCADE')
    op.drop_constraint('prev_psp_details_ibfk_1', 'prev_psp_details', type_='foreignkey')
    op.create_foreign_key(None, 'prev_psp_details', 'applications', ['arn'], ['arn'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prev_psp_details', type_='foreignkey')
    op.create_foreign_key('prev_psp_details_ibfk_1', 'prev_psp_details', 'applications', ['arn'], ['arn'])
    op.drop_constraint(None, 'payment_details', type_='foreignkey')
    op.create_foreign_key('payment_details_ibfk_1', 'payment_details', 'applications', ['arn'], ['arn'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_ibfk_2', 'appointments', 'passport_offices', ['po_code'], ['po_code'])
    op.create_foreign_key('appointments_ibfk_1', 'appointments', 'applications', ['arn'], ['arn'])
    op.drop_constraint(None, 'appointment_schedules', type_='foreignkey')
    op.create_foreign_key('appointment_schedules_ibfk_1', 'appointment_schedules', 'passport_offices', ['po_code'], ['po_code'])
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_ibfk_1', 'applications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'applicant_family', type_='foreignkey')
    op.create_foreign_key('applicant_family_ibfk_1', 'applicant_family', 'applications', ['arn'], ['arn'])
    op.drop_constraint(None, 'applicant_addresses', type_='foreignkey')
    op.create_foreign_key('applicant_addresses_ibfk_1', 'applicant_addresses', 'applications', ['arn'], ['arn'])
    op.drop_index(op.f('ix_police_stations_id'), table_name='police_stations')
    op.drop_table('police_stations')
    # ### end Alembic commands ###
