"""applications table altered

Revision ID: 9da826847adb
Revises: 38bb9bec42f8
Create Date: 2023-07-13 19:24:55.410106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da826847adb'
down_revision = '38bb9bec42f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'dob')
    # ### end Alembic commands ###
