"""applications table altered

Revision ID: b68faa99196a
Revises: 9da826847adb
Create Date: 2023-07-13 19:31:23.428736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b68faa99196a'
down_revision = '9da826847adb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('applications', sa.Column('app_name', sa.String(length=40), nullable=True))
    op.drop_column('applications', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('name', mysql.VARCHAR(length=40), nullable=True))
    op.drop_column('applications', 'app_name')
    op.drop_column('applications', 'marital_status')
    # ### end Alembic commands ###
