"""appointments schedule table altered

Revision ID: f2fbb80543c1
Revises: 3ef40017fe53
Create Date: 2023-07-15 22:15:53.533344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fbb80543c1'
down_revision = '3ef40017fe53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_schedules', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment_schedules', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
